### ISSUE TITLE
Access $request object on rateLimitsExceeded

### ISSUE THREAD

**Issue by ajoudeh** [thamtech/yii2-ratelimiter-advanced#1]
Dear, 

when us this code
`
'on rateLimitsExceeded' => function($event) {
    if ($request->getUserIp() == '127.0.0.1') {
        $event->handled = true;
    }
    // other handlers will not be invoked when IP is 127.0.0.1
}
`

i get this error: Call to a member function get() on null. $request is NULL

**Comment by tyler-ham** [comment]
This is a mistake in the documentation (in the Filtering Events section of README.md). The `$request` is an undefined variable and should instead be `$event->context->request`.

The example in its entirety should be:

```php
<?php
...
'on rateLimitsExceeded' => function($event) {
    if ($event->context->request->getUserIp() == '127.0.0.1') {
        $event->handled = true;
    }
    // other handlers will not be invoked when IP is 127.0.0.1
}
...
```
