### ISSUE TITLE
Rate limit is only displayed in request headers for GET requests

### ISSUE THREAD

**Issue by irinaioanav411** [thamtech/yii2-ratelimiter-advanced#5]
Hi,

I'm trying to put a rate limit on a POST action form (action-xhr as I use AMP validation), but it does not seem to add the headers to the request, although it's working on GET requests.

What might be the issue?

**Comment by tyler-ham** [comment]
Can you post your rate limit configuration and action code?

If you are using the `RateLimitHeadersHandler`, it sets the headers in the `yii\web\Response` object (`Yii::$app->getResponse()` by default). One possible issue is if your POST action calls `exit()` abruptly at some point. In that case, the headers that were set in the response object by `RateLimitHeadersHandler` may never be sent to the browser.

**Comment by irinaioanav411** [comment]
Yes, that was it! Thanks!!

În mie., 12 mai 2021 la 20:08 Tyler Ham ***@***.***> a scris:
