### ISSUE TITLE
Limit GET or POST for action only?

### ISSUE THREAD

**Issue by 1Luc1** [thamtech/yii2-ratelimiter-advanced#6]
I was wondering - and couldn't find anything within the docs - if its possible to limit only if an action is called within an POST request? Since I have an action which also will be called as GET and has an POST part, which i want to limit.

```php
    public function actionLogin()
    {
        $model = $this->module->model("LoginForm");

        // load post data and login
        $post = Yii::$app->request->post();
        if ($model->load($post) && $model->validate()) {
            $returnUrl = $this->performLogin($model->getUser(), $model->rememberMe);
            return $this->redirect($returnUrl);
        }

        return $this->render('login', compact("model"));
    } 
```

**Comment by tyler-ham** [comment]
Good question! Yes, you should be able to use the `active` property in your rate limit definition like the following:

```php
'active' => Yii::$app->request->isPost,
```

This way, the rate limiter is only active when the request uses the POST method.

In the main readme (https://github.com/thamtech/yii2-ratelimiter-advanced#introduction), there is an example of the `active` property in the Advanced Example's `user-admin` definition:

```php
// only applies this particular rate limit for users who are admins
'active' => Yii::$app->user->getIdentity()->isAdmin(),
```

The `active` property can be any scalar value that will be cast to a boolean. It can also be a callable with the signature `function($context, $rateLimitId)`.

**Comment by 1Luc1** [comment]
thanks, work like a charm!
