### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by srakl** [thamtech/yii2-ratelimiter-advanced#7]
in my code i have this code to limit by user id, and disable the ratelimiter for the `actionUserNotification()`

```
'rateLimiter' => [
                    'class' => 'thamtech\ratelimiter\RateLimiter',
                    'except' => ['user-notification'],
                    'components' => [
                         'rateLimit' => [
                            'definitions' => [
                                'user' => [
                                    'limit' => 1000,
                                    'window' => 3600,
                                    'identifier' => $_GET['user-id'],
                                ],
                            ],
                        ],
                        'allowanceStorage' => [
                            'cache' => 'cache',
                        ],
                    ],
                    'as rateLimitHeaders' => [
                        'class' => 'thamtech\ratelimiter\handlers\RateLimitHeadersHandler',
                        'prefix' => ['X-Rate-Limit-', 'X-RateLimit-'],
                    ],
                    'as retryAfterHeader' => 'thamtech\ratelimiter\handlers\RateLimitHeadersHandler',
                    'as tooManyRequestsException' => 'thamtech\ratelimiter\handlers\TooManyRequestsHttpExceptionHandler',
                ]
     
````

the code works, but when `actionUserNotification()` is run, i get an error in my logs `undefined array key "user-id"`

how to i disable or exclude `actionUserNotification()` ? Thanks

**Comment by srakl** [comment]
Got it,

added 

`'active' => (!empty($_GET['user-id'])) ? true : false`

if `used-id` is empty, i added another definition for IP

**Comment by tyler-ham** [comment]
PHP attempts to populate the identifier as the value of `$_GET['user-id']` well before the `RateLimiter` class has a chance to check the action against the `user-notification` exception.

You can define the identifier as a callback instead, which will defer attempting to resolve `$_GET['user-id']` until it is needed:

```php
'identifier' => function($context, $rateLimitId) {
    return $_GET['user-id'];
},
```

In either case, you may consider checking for the existence of `$_GET['user-id']` before using it. For example, you might set a default value when it is missing:

```php
!empty($_GET['user-id']) ? $_GET['user-id'] : false
```

**Comment by srakl** [comment]
Thank you! that worked!
